server:
  port: 8065
spring:
  application:
    name: authzww
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/ #Servse 地址
  instance:
    hostname: 127.0.0.1
    instance-id: ${hostname}:${server.port}  #向注册中心暴露服务提供者的IP和端口
    prefer-ip-address: true
    #公钥私钥 暂时放在配置文件中，后期放redis中
  publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCgkNmIJMiRWEc8SA2F7dtQrbCO/AlyFCQXaidQGBFvqk2mizKBTZC6DCHhWcitf6NAe3BDq22NBxuKInxVy8ArWQJRyAqBnUNjetzD7rkwdcDedkAe07sbCSKBtzfvsybc5tfppRPRoc+d+HVUX0qbe4uCGCI06Cw4jGMqapgl8wIDAQAB
  privateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAKCQ2YgkyJFYRzxIDYXt21CtsI78CXIUJBdqJ1AYEW+qTaaLMoFNkLoMIeFZyK1/o0B7cEOrbY0HG4oifFXLwCtZAlHICoGdQ2N63MPuuTB1wN52QB7TuxsJIoG3N++zJtzm1+mlE9Ghz534dVRfSpt7i4IYIjToLDiMYypqmCXzAgMBAAECgYB61VUU6c7mIfqdCyINSyF0Xuuq9vTi6LWTlAnvI/pyyn4M4oAImyYUriNdGiqDUBm7wrLnkcWFFeLjke48VFr1kIyPEbWJGrHRroBAcMThbI3SX3pUGEcg7QMHILvLCg+fmmIw/RSdK/ose0mGTP3EDd2IzaUII86knMmaL0nsQQJBAP0YDVuSVpNd4uVbKNHZkGiF8JbiU2HRk3nqayVNUMkFNlAqLW3g/9lcP51xNirL3vdkv1x71Q/7Pdb9qfUjeXcCQQCiaNGwIev3f+OEtR8sCsqRa8o5qMZoQWOsSId1BXrllWhyejUhzlHXXST5zk/YEvi/8jHoTwz/qFZwC1AMXxZlAkEAwiSRGo1GnASI6CblSRP7EjKsOxGhpId++SY4yoRkU88LurKf5omRuMpqgfs18d4xStSddfQHnBq9dQ1gMgrkQQJAPAkHSlafxZPO5OWXKk6q5uqzjHDpNuzFDZCaEhX+ghOi0n5+WYrNEhFqc7ViKnuI3FuJO1jNc0wk97IW2xvjSQJBAOviN8pJBNDC4V0aKUEilNkQPRp626Bq1w6RG/phjt7mrSw+tKNPqsewqcE7QljJQ45V8Oc2LrZbQ70LhU2myeA=
